### ISSUE TITLE
atom freeze after update 2.1.0 in Windows 10

### ISSUE THREAD

**Issue by KamiGim** [atom-community/autocomplete-paths#118]

**Comment by saschagehlich** [comment]
@KamiGim Please provider some more information:

* How large is the project you're using?
* Does your project use git?
* When exactly does atom freeze?

**Comment by KamiGim** [comment]
1. not large I guess
2. yes use git 
![image](https://user-images.githubusercontent.com/17401507/29228322-89a850ee-7f03-11e7-90d1-b0039579ef58.png)

**Comment by KamiGim** [comment]
1. not large I guess
2. yes I use git
![image](https://user-images.githubusercontent.com/17401507/29228443-ec502a3c-7f03-11e7-9901-1bd815df21c3.png)

**Comment by saschagehlich** [comment]
This module doesn't lock up for no reason, I believe the project you're working on doesn't look huge, but it is pretty large. Do you have folders like `node_modules` or `bower_components` that contain large amounts of dependencies and are not in .gitignore?

**Comment by KamiGim** [comment]
No node_modules is in .gitignore
![image](https://user-images.githubusercontent.com/17401507/29228703-0f133aa4-7f05-11e7-9f4d-e7e5524a733d.png)
but if I use this version,it works fine
![image](https://user-images.githubusercontent.com/17401507/29228778-66b93a7e-7f05-11e7-9b50-e5d24d3060fb.png)

**Comment by saschagehlich** [comment]
Are you opening a folder that contains *multiple* git directories instead of opening a single git directory?

**Comment by KamiGim** [comment]
yes I open two project folders
right now I also try to open only one folder. it still freezes
maybe I should use older version instead

**Comment by ddirks** [comment]
Similar problem for me on Win 10 Pro x64, even when opening my user account Atom config folder/project, which is not large. I got the "Rebuilding paths cache" message in the lower right corner, and then the "Editor is not responding" error dialog. I tried the "Keep Waiting" option five times to be sure it wasn't just thinking really hard about something, but I finally had to "Force Close." Restarting Atom put it right back into the unresponsive "Rebuilding paths cache" state.

To get out of the loop, I first tried manually deleting the ~/.atom/packages/autocomplete-paths directory. On restarting Atom, I still saw the "Rebuilding paths cache" message and the editor was still unresponsive, giving the same error dialog. Next, I restarted Atom with the --clear-window-state flag, which allowed the editor to start normally.

Finally, thinking that the --clear-window-state might have cleared up whatever the problem was, I tried reinstalling autocomplete-paths again. Sadly, I saw the same behavior after the second install, and had to do another cycle of delete & clear.

**Comment by saschagehlich** [comment]
I have just released 2.2.0 which sets a file limit (2000 by default). Please check it out.
If you get the message `Maximum file count exceeded`, then for some reason atom is not recognizing ignored files. I've added a [troubleshooting guide](https://github.com/atom-community/autocomplete-paths/wiki/Troubleshooting#maximum-file-limit-exceeded) to our wiki.

**Comment by jlowin** [comment]
@saschagehlich I came here looking for why that 2000 message popped up. In my case I know it's because I have a project folder that contains multiple git repos, one of which has a node_modules folder. 

However, my Atom locks up despite displaying the 2000 message warning. By disabling/reenabling the extensions, I can confirm that autocomplete-paths is the cause of the freeze. So for what it's worth, the message is informative but doesn't seem to be preventing the core issue. 

I never experienced this freeze until this morning when I updated to the 2.X branch. I haven't gone through the code except at a high level, but perhaps some new feature is much more computationally expensive with large projects than it would appear to be?

**Comment by dhawton** [comment]
Just updated.. not getting that message but same symptoms.. and now I'm stuck.

**Comment by saschagehlich** [comment]
@jlowin Thanks for reporting this. I'll have access to a windows machine tomorrow and will look into this.

**Comment by linjialiang** [comment]
me too， This issue is caused by a conflict with ererviewer@1.2.0？

**Comment by linjialiang** [comment]
autocomplete-paths 2.5.0 
There is still no completion path complement

**Comment by linjialiang** [comment]
Community Packages (30) C:\Users\kc_em\.atom\packages
├── advanced-open-file@0.16.6
├── atom-autocomplete-php@0.25.6
├── atom-beautify@0.30.5
├── atom-clock@0.1.13
├── atom-ternjs@0.18.3
├── autoclose-html@0.23.0
├── autocomplete-paths@2.5.0
├── autocomplete-php@0.3.7
├── autoprefixer@3.7.1
├── color-picker@2.2.5
├── docblockr@0.11.0
├── emmet@2.4.3
├── file-icons@2.1.10
├── highlight-line@0.12.0
├── highlight-selected@0.13.1
├── indent-guide-improved@1.4.13
├── markdown-scroll-sync@2.1.2
├── minimap@4.29.6
├── minimap-find-and-replace@4.5.2
├── minimap-highlight-selected@4.6.1
├── monokai@0.24.0
├── open-in-browser@0.5.2
├── pigments@0.40.2
├── project-viewer@1.2.0
├── pure-syntax@0.3.0
├── relative-numbers@0.8.0
├── script@3.15.0
├── sync-settings@0.8.2
├── vim-mode-plus@0.96.2
└── vim-mode-plus-ex-mode@0.9.1

**Comment by jlowin** [comment]
@saschagehlich thank you! I did not read the title of this issue closely enough; I am actually using a Mac.

**Comment by saschagehlich** [comment]
You could try adding node_modules to your ignored names core setting

**Comment by jlowin** [comment]
That did it, thanks! I sort of assumed it was in there by default to be honest.

**Comment by saschagehlich** [comment]
I was able to reproduce the issue on Windows 10 and will investigate

**Comment by saschagehlich** [comment]
Apparently the many pathwatchers are causing this

**Comment by saschagehlich** [comment]
Due to [limitations in the Windows implementation of node-pathwatcher](https://github.com/atom/node-pathwatcher/issues/70) I disabled path watching for Windows in 2.6.0. This fixes the freezing issues.

**Comment by KamiGim** [comment]
cool thanks It's working now

**Comment by ddirks** [comment]
Here's a data point with the 2.6.0 version (Win 10 x64): I installed and opened a large project and got the "Maximum file limit of 2000 files exceeded" (as expected, I suppose.) In addition, I *also* continued to see the  "Rebuilding paths cache" message on the status line. Interestingly, this message did not permanently block other operations in the UI (as it did previously with the 2.1.0/2.2.0 versions), but it was obviously running. (Switching between tabs would take 10+ seconds, for example.)

So: no --clear-window-state required to recover, but still unusable (for me) with autocomplete-paths 2.6.0 installed.

Is it possible that the "Rebuilding paths cache" state is persisting somewhere even when the package is uninstalled/reinstalled?
