### ISSUE TITLE
Running the cache collection in a WebWorker/WorkerThread

### ISSUE THREAD

**Issue by aminya** [atom-community/autocomplete-paths#231]
Currently, this package sets a limit on the number of files it can process so it does not block the main thread. If we use a native module or run the JavaScript on workers, we can remove this limitation.

Related issues that this improvement can potentially fix:
#221
#164
#204
#205
#219
#157
#186

**Comment by aminya** [comment]
One of the hot parts of the code is this function call: https://github.com/atom-community/autocomplete-paths/blob/b6d3b09d76397d19ecb3f89fc2379993210161f0/lib/paths-cache.js#L154

It uses some Atom API (directory.getEntries) to get the Files or Directories under a certain directory.

**Comment by lierdakil** [comment]
WebWorkers in Atom can't access Node API. Not entirely sure why it's that way, but perhaps for a good reason, e.g.

> The only way to load a native module safely for now, is to make sure the app loads no native modules after the Web Workers get started.
[(source)](https://www.electronjs.org/docs/tutorial/multithreading)

(this condition is pretty much impossible to guarantee in Atom as far as I can tell)

So the only way to make caching non-blocking that I currently can think of is splitting it out into a separate worker process. But that creates a potential bottleneck in JSON deserialization if the number of files is large (on the order of tens of thousands), since processes in Node can't share memory. This can be worked around perhaps by offloading filtering onto the worker process as well, but that creates some latency concerns.

That is to say, this is a bit complicated.

**Comment by aminya** [comment]
> WebWorkers in Atom can't access Node API. Not entirely sure why it's that way, but perhaps for a good reason, e.g.

Using Node API is enabled in this PR:
https://github.com/atom/atom/pull/21139

The community version of Atom already supports Node API in the web workers. For the official Atom, it is just a switch that Atom maintainers need to enable. @sadick254 @darangi
