### ISSUE TITLE
Performance issue on large projects

### ISSUE THREAD

**Issue by david-byng** [atom-community/autocomplete-paths#45]
On an ionic+cordova project with 955 files in the www folder, there are slowdowns while typing with autocomplete-paths enabled.

Running atom 0.177.0 on ubuntu 14.04, with the following packages:

|  |  |  |
| --- | --- | --- |
| Linter | atom-color-highlight | autocomplete-emojis |
| autocomplete-paths | autocomplete-plus | cucumber |
| file-icons | highlight-selected | lcov-info |
| auto-indent | linter-jshint | linter-php |
| merge-conflicts | minimap | minimap-color-highlight |
| minimap-git-diff | minimap-highlight-selected | minimap-selection |
| phpunit |  |  |

Slowdown only occurs with autocomplete-paths enabled, speeds back up when only this package is disabled.

**Comment by david-byng** [comment]
Having looked into how autocomplete-paths works, it looks like the number of files should have no impact, but number of files within the current folder should.
However there are only 12 files in the current directory. I am *not* using a SSD though, and autocomplete-paths looks to make x+2 FS calls, where x is the number of files in the current directory, on each pass of [`findSuggestionsForPrefix`](https://github.com/atom-community/autocomplete-paths/blob/master/lib/paths-provider.coffee#L53). I'm not sure how often autocomplete-plus calls autocomplete-paths; could these fs calls be related?

**Comment by joefitzgerald** [comment]
autocomplete-plus calls autocomplete-paths every 100ms or every keystroke, whichever has a longer interval. 

You are correct that autocomplete-paths could be much more intelligent about caching the information about the filesystem related to the current editor, and in doing so become more performant. It should also be updated to build suggestions asynchronously and use async `fs` functions instead of the sync equivalents it currently uses.

The combination of these changes would provide a significant performance improvement, and need to be done. Im happy to accept PRs, until @park9140 or I have the time to make these changes.

**Comment by dannyfritz** [comment]
I experience huge performance hits when I have this package enabled too. I have an SSD and my project is only about 10 files. The problem seems to lie in `fs.statSync` and not in this package. Maybe moving to an async `fs.stat` would help, even if data could be 100ms out of date?
![image](https://cloud.githubusercontent.com/assets/315788/7185249/38588908-e427-11e4-9ba5-e63e97613eb7.png)

**Comment by park9140** [comment]
@joefitzgerald, @dannyfritz is right about the performance problem.  `fs.statSync` locks the worker thread until the file access is done.  Now that we have async you can probably solve 100% of performance issues with this by calling `fs.stat`.   

Threw together a quick example of what would need to happen in order to make this async in #53 if anyone wants to finish it.

**Comment by dannyfritz** [comment]
I went ahead and poked around with it. (Thanks for the starting point @park9140 :+1:) I was getting really frustrated with debugging coffeescript so I converted it to JS and proceeded from there. And because of that, I can't really show a clean diff between the 2. And it probably can't get merged in directly without someone first interpreting it as CoffeeScript.

But, the main problem was that it was attempting to do `fs.statSync` on URL's and other invalid directories that would timeout after ~20 seconds. So the editor would be frozen on that for a while waiting for the timeout. Just making this 1 call async appears to solve it for me: https://github.com/atom-community/autocomplete-paths/blob/4f56ff25e30365a7d8a2c7f2b9d1275d5294b2bd/lib/paths-provider.coffee#L70

With this async version, the timeouts eventually just reject the Promise and nobody is the wiser. And you can continue typing as it times out.

**Comment by park9140** [comment]
@dannyfritz, I'm totally with you on the coffeescript thing. I was really bad at it at first. http://js2.coffee/ This tool made things alot easier.  Allows you to see kind of what it should look like in coffeescript then you can clean up with the coffee linter after that.

**Comment by capaj** [comment]
@park9140 thanks for the link. The next time someone asks me why I dislike coffescript, all I have to do is point them there. The example that they have is clearly demonstrating it. Great stuff

**Comment by rugk** [comment]
Also experienced performance issues. As this is really annoying it should really be fixed in the next time.

I've uploaded a JSON file of the timeline created with the Chromium dev tools, here: https://gist.github.com/rugk/d672a1c1f364a175caa2

**Comment by dannyfritz** [comment]
I don't mean this as a jest or anything, but I have moved to this other package to autocomplete paths: https://atom.io/packages/autocomplete-modules

**Comment by crazy4groovy** [comment]
(Relates to issue #71)

**Comment by arturparkhisenko** [comment]
Duplicated issues (author can easy close them):
https://github.com/atom-community/autocomplete-paths/issues/83
https://github.com/atom-community/autocomplete-paths/issues/95
https://github.com/atom-community/autocomplete-paths/issues/91
https://github.com/atom-community/autocomplete-paths/issues/84
https://github.com/atom-community/autocomplete-paths/issues/71
And track all progress in this **single** issue.

**Maybe someone can help us fix the lags?** i'll try soon, but i'm not sure that i'm capable to fix that.
My screenshot/record:
![atom-lag](https://cloud.githubusercontent.com/assets/139212/20591042/35136f6a-b22f-11e6-9f5b-da41e47dfae7.png) 🔥 🚒

**Comment by saschagehlich** [comment]
2.0.0 provides a much better experience, as it indexes the project on startup and does incremental index updates when something inside the project changes.

**Comment by brandontamm** [comment]
How can we download 2.0? I work on Magento projects using docker. All projects are around 60k files so I'm literally not even able to work with 1.19.6 and have to switch if I can't get ahold of a fix
