### ISSUE TITLE
Path segment doesn't complete on Enter, v 1.0.2

### ISSUE THREAD

**Issue by smlombardi** [atom-community/autocomplete-paths#50]
I have autocomplete plus, 2.2.0, set to complete suggestions on enter, and it works.

However, I added autocomplete-paths, and the paths are correctly suggested but do not complete on enter, it just dismisses the popup and inserts a return.

I can't use tab since it completes with Emmet.  Which is why I set autocomplete plus settings to "enter"

**Comment by jordanbtucker** [comment]
Open the **Key Binding Resolver** (<kbd>Ctrl</kbd>+<kbd>.</kbd> / <kbd>Cmd</kbd>+<kbd>.</kbd>), then try again. What action is taking precedence over `autocomplete-plus:confirm`?

**Comment by jaypanares** [comment]
I'm also experiencing this issue.  When I open Keybinding Resolver I don't see an entry for `autocomplete-plus:confirm`.  I'm using version 0.188.0 on Windows 8.1.  I have Emmet installed as well as both `autocomplete-plus` and `autocomplete-paths`.

**Comment by joseluisq** [comment]
@jordanbtucker exists a conflict between `atom-emmet` and `atom-autcomplete-paths` because both uses the `tab` key. 
Also when I press the `enter` key on some path menu item doesn't work.

Here screenshot of **Key Binding Resolver**

![image](https://cloud.githubusercontent.com/assets/1700322/13381304/c257de52-de26-11e5-8980-ad99880f5b1e.png)

Only I can see `autocomplete-plus:confirm` when `atom-emmet` is disabled and all works fine.

**Comment by jordanbtucker** [comment]
To fix this `autocomplete-plus` + `emmet` issue, please see https://github.com/emmetio/emmet-atom/issues/225#issuecomment-82669798.

**Comment by joseluisq** [comment]
@jordanbtucker cool!
Thanks!
